@doc raw"""
    compute_function_of_measurements(
        # ARGUMENTS
        comm::MPI.Comm;
        # KEYWORD ARGUMENTS
        f::Function,
        datafolder::String,
        measurements::AbstractVector{<:NamedTuple},
        num_bins::Int = 0,
        pIDs::Vector{Int} = Int[],
    )

    compute_function_of_measurements(;
        # KEYWORD ARGUMENTS
        f::Function,
        datafolder::String,
        measurements::AbstractVector{<:NamedTuple},
        num_bins::Int = 0,
        pIDs::Union{Int,Vector{Int}} = Int[]
    )

Calculate the mean and error associated with computing a function of measured quantities.

The measurements that are passed are arguments of the function to evaluate are specified by the vector
of named tuples `measurements`. The keys of the named tuple used to specify the measurements are given below:

- `name::String`: Name of measurement function.
- `type::String`: Specifies whether the measurement is a "GLOBAL" or "LOCAL" measurement, or a "EQUAL-TIME", "TIME-DISPLACED" or "INTEGRATED" correlation measurement.
- `id::Int`: If a "LOCAL" measurement, then this in a single integer specifying an ID value.
- `id_pair::NTuple{2,Int}`: If a standard correlation measurement, then specifies the ID pair for the correlation measurement.
- `R::NTuple{D,Int}` xor `K::NTuple{D,Int}`: Specifies either a displacement vector or momentum point in `D` dimensions if the measurement is a correlation measurement.
- `τ::Float64` xor `l::Int`: Imaginary-time or imaginary-time slice used if a "TIME-DISPLACED" correlation measurement is specified.

# Keyword Arguments

- `f::Function`: The function to evaluate.
- `datafolder::String`: Output directory generated by SmoQyDQMC simulation.
- `measurements::AbstractVector{NamedTuple}`: Vector of named tuples specifying the measurements used as function arguments.
- `num_bins::Int = 0`: Number of bins used to compute statistics. If zero then use all number of bins.
- `pIDs = Int[]`: Process ID's used when measuring function of correlation measurements. If is `Int[]`, then all process ID's are used.
"""
function compute_function_of_measurements(
    # ARGUMENTS
    comm::MPI.Comm;
    # KEYWORD ARGUMENTS
    f::Function,
    datafolder::String,
    measurements::AbstractVector{<:NamedTuple},
    num_bins::Int = 0,
    pIDs::Vector{Int} = Int[],
)

    # number of MPI processes
    N_mpi = MPI.Comm_size(comm)

    # determine relevant pIDs
    pIDs = isempty(pIDs) ? collect(0:N_mpi-1) : pIDs
    pID = pIDs[MPI.Comm_rank(comm) + 1]

    # if root process
    isroot = iszero(pID)

    # get HDF5 filename containing binned data
    filename = joinpath(datafolder, "bins", "bins_pID-$(pID).h5")

    # open HDF5 file containing binned data
    H5BinFile = h5open(filename, "r")

    # get the binned sign data
    binned_sign = read(H5BinFile["GLOBAL/sgn"])

    # get number of bins per process
    n_bins = length(binned_sign)
    num_bins = iszero(num_bins) ? n_bins : num_bins
    @assert iszero(mod(num_bins, n_bins)) "num_bins = $(num_bins) is not a factor of the number of data bins per pID, $(n_bins)."

    # rebin the sign data
    binned_sign = rebin(binned_sign, num_bins)

    # gather sign data onto root process
    binned_sign = MPI.gather(binned_sign, comm)
    binned_sign = isroot ? vcat(binned_sign...) : nothing

    # get the data type
    R = isroot ? real(eltype(binned_sign)) : nothing

    # initialize vector to contain binned values
    binned_correlations = isroot ? Vector{Vector{Complex{R}}}(undef, 0) : nothing

    # iterate over correlations
    for measurement in measurements
        
        # read in the binned correlation
        binned_correlation = rebin(_read_measurement_bins(H5BinFile, measurement), num_bins)

        # gather the binned correlation data
        binned_correlation = MPI.gather(binned_correlation, comm)

        # record the correlation data
        if isroot
            push!(binned_correlations, vcat(binned_correlation...))
        end
    end

    # if is root process
    if isroot

        # initialize version of function that take the sign as the first argument
        # and ensure re-weighting is performed when evaluating the function
        F(z...) = f(map(x->x/z[1], z[2:end])...)

        # calculate the composite correlation
        C, ΔC = jackknife(F, binned_sign, binned_correlations..., bias_corrected=false)
    else

        C, ΔC = nothing, nothing
    end

    # broadcast the number to all processes
    C = MPI.bcast(C, comm)
    ΔC = MPI.bcast(ΔC, comm)

    # close the H5 file
    close(H5BinFile)

    return C, ΔC
end

function compute_function_of_measurements(;
    # KEYWORD ARGUMENTS
    f::Function,
    datafolder::String,
    measurements::AbstractVector{NamedTuple},
    num_bins::Int = 0,
    pIDs::Union{Int,Vector{Int}} = Int[]
)

    # determine relevant process IDs
    pIDs = isa(pIDs, Int) ? [pIDs,] : pIDs
    if isempty(pIDs)
        pIDs = collect( 0 : length(readdir(joinpath(datafolder,"bins")))-1 )
    end

    # number of process IDs
    N_pID = length(pIDs)

    # open all the input HDF5 bin files
    H5BinFiles = [h5open(joinpath(datafolder, "bins", "bins_pID-$(pID).h5"), "r") for pID in pIDs]

    # get the total number of bins per pID
    n_bins = read_attribute(H5BinFiles[1], "N_BINS")

    # determine the number of bins to use to calculate statistics
    num_bins = iszero(num_bins) ? n_bins : num_bins
    @assert iszero(mod(num_bins, n_bins)) "num_bins = $(num_bins) is not a factor of the number of data bins per pID, $(n_bins)."

    # read in binned sign data
    binned_sign = vcat((
        vcat((rebin(read(h5["GLOBAL/sgn"]), num_bins) for h5 in H5BinFiles)...)
    )...)

    # read in the binned sign data
    binned_correlations = [
        (vcat((rebin(_read_measurement_bins(h5, measurement),num_bins) for h5 in H5BinFiles)...)
         for measurement in measurements)...
    ]

    # initialize version of function that take the sign as the first argument
    # and ensure re-weighting is performed when evaluating the function
    F(z...) = f(map(x->x/z[1], z[2:end])...)

    # calculate the composite correlation
    C, ΔC = jackknife(F, binned_sign, binned_correlations..., bias_corrected=false)

    # close all the H5 bin files
    close.(H5BinFiles)

    return C, ΔC
end


# read in binned measurement values
function _read_measurement_bins(
    h5::HDF5.File,
    measurement::NamedTuple
)

    # if a global measurement
    if measurement.type == "GLOBAL"

        # read in global measurement
        binned_measurement = _read_global_measurement_bins(h5, measurement)

    # if a local measurement
    elseif measurement.type == "LOCAL"

        # read in local measurement
        binned_measurement = _read_local_measurement_bins(h5, measurement)

    # if a correlation measurement
    else
        # read in correlation measurement
        @assert haskey(measurement, :type)
        @assert haskey(measurement, :id_pair)
        binned_measurement = _read_correlation_bins(h5, measurement)
    end

    return binned_measurement
end

# read in the binned global measurement values
function _read_global_measurement_bins(
    h5::HDF5.File,
    measurement::NamedTuple
)

    @assert haskey(GLOBAL_MEASUREMENTS, measurement.name)
    binned_measurements = read(h5["GLOBAL"][measurement.name])

    return binned_measurements
end

# read in the binned local measurement values
function _read_local_measurement_bins(
    h5::HDF5.File,
    measurement::NamedTuple
)

    @assert haskey(LOCAL_MEASUREMENTS, measurement.name)
    @assert isa(measurement.id, Int)
    binned_measurements = h5["LOCAL"][measurement.name][:,measurement.id]

    return binned_measurements
end
