name = "SmoQyDQMC"
uuid = "00e12d65-277b-447e-9c1d-a17422dd36f5"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
